FROM python:3.7-slim

WORKDIR /app

RUN pip install -U scikit-learn numpy

COPY kubeflow_pipelines_preprocess.py ./kubeflow_pipelines_preprocess.py

ENTRYPOINT [ "python", "kubeflow_pipelines_preprocess.py" ]